site_name: SRL Docs
nav:
  - Home: index.md
#  - Getting Started:
#      - Introduction: getting-started/introduction.md
#      - Containerlab: getting-started/containerlab.md
#  - Configuration:
#    - Introduction: configuration/introduction.md
#    - System:
#        - tacacs: configuration/system/tacacs.md
#    - Interfaces:
#        - routed interface: interfaces/routed.md
#        - bridge interface: interfaces/bridged.md
#        - lag: interfaces/lag.md
#        - vlan: interfaces/vlan.md
#    - Network-instnces:
#        - Vrf: network-instances/vrf.md
#        - Irb: network-instances/irb.md
  - Python CLI Plugin: 
    - Introduction: python/introduction.md
    - CLI Show plugin: python/show.md
    - CLI Tools plugin: python/tools.md
    - SRLinux Python Plugins:
        - command: python/command.md
        - syntax: python/syntax.md
        - schemanode: python/schemanode.md
        - data: python/data.md
        - datachildrenoftype: python/datachildrenoftype.md
        - output: python/output.md
#  - NDK Agents:
#    - Introduction: ndk-agents/introduction.md
#    - Golang: ndk-agents/golang.md
#    - Python: ndk-agents/python.md
#    - Examples:
#        - Test Agent: ndk-agents/examples/testagent.md
#        - Git CLient: ndk-agents/examples/git-client.md
#  - Usage: usage.md

site_author: Wim Henderickx
site_description: >-
  SRL documentation

repo_name: srl-wim/srldocs
repo_url: https://github.com/srl-wim/srldocs
edit_uri: ""
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
 
  language: en
  palette:
    scheme: preference
    # primary: black
    accent: pink
  font:
    text: Manrope
    code: Fira Mono
  #icon:
  #  logo: images/srl.png   
  favicon: images/srl.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/srl-wim

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde